import type { Metadata } from "next";
import { Roboto_Condensed, Roboto_Flex } from "next/font/google";
import "./globals.css";


const robotoFlex = Roboto_Flex({
  variable: "--font-roboto-flex",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${robotoFlex.variable} ${robotoCondensed.variable}`}>
        {children}
      </body>
    </html>
  );
}
